#!/usr/bin/env bash

# first setup and install require component
apt -y update --fix-missing && apt -y upgrade

apt -f --no-install-recommends install -y \
    ca-certificates \
    wget \
    git \
    curl \
    gnupg \
    lsb-release \
    nano \
    nmap \
    php \
    python-is-python3 \
    python3-pip


# setup for install docker
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin